## 맛있는 절약 : 평가용 dataset 생성
1. find_keyIngredients_tasty : (사전 생성) 레시피의 핵심 맛과 핵심 재료를 판단
2. generate_food_group_radio : (사전 생성) 레시피의 식품군을 판별
3. fridge_recipe_transform : (기능) 냉장고 재료 대체 
4. simple_recipe_transform : (기능) 레시피 간소화 
5. balance_nutrition : (기능) 영양 맞춤형 레시피 

## 일반적인 평가용 dataset 생성 case
- 검색한 것이 질문과 관련이 있는가?
- 답변이 질문과 관련이 있는가?
- 답변을 검색한 문서 안에서 답변한 것인가?(할루시네이션 check)

## 한계
검색한 결과에 대한 정확한 기준 데이터(Ground truth) 구축이 사실상 어려움
따라서, 검색한 결과에 대한 Ground truth가 존재한다면 모두 데이터셋으로 활용하고, 아니라면 질문과 답변만으로 데이터셋을 구축하여 활용함
⇒ 우리는 레시피 생성시에 RAG가 없기 때문에 질문과 답변만으로 데이터셋을 구축해서 활용함

## 레시피 dataset
spicy_level, type_key, method_key, servings를 기준으로 각각 중복되지 않은 행만 추출

In [131]:
import pandas as pd
df_recipeinfo = pd.read_csv("data/diverse_recipes_dataset.csv")
df_recipeinfo.describe()

,_id,title,type_key,method_key,servings,cooking_time,difficulty,ingredients,cooking_steps,tips,recipe_type,spicy_level
count,35,35,35,35,34,33,33,35,35,35,35,35
unique,35,35,12,13,5,7,2,35,35,17,35,6
top,67610699846f9e5eb975e532,연어샐러드,반찬,끓이기,1인분,30분 이내,초급,"['연어(150g)', '레몬(1/4개)', '발사믹식초(50g)', '어린잎채소(30g)', '후춧가루(0.01g)', '올리브오일(20g)']","['1. 연어는 깍둑썰기한다.', '2. 썰어 놓은 연어는 후춧가루와 레몬으로 마리네이드한다.', '3. 어린잎은 찬물에 담궈둔다.', '4. 담궈 놓은 어린잎을 체에 받쳐 물기를 뺀다.', '5. 레몬과 올리브오일을 섞는다.', '6. ?번에 발사믹소스를 넣고 연어 샐러드 양념을 만들고, 접시에 연어와 물기를 뺀 어린잎을 담는다.']",[],"['고단백', '저칼로리', '해산물', '샐러드']",매운맛없음
freq,1,1,10,10,12,14,29,1,1,19,1,23

In [132]:
df_userinfo = pd.read_csv('data/persona_csv.csv')
df_userinfo.describe()

,persona,user_allergy_ingredients,user_dislike_ingredients,user_spicy_level,user_cooking_level,user_owned_ingredients,user_basic_seasoning,must_use_ingredients
count,10,10,10,10,10,10,10,10
unique,10,4,10,5,3,10,10,8
top,유미,[],[],3단계,초급,"['닭가슴살', '두부', '브로콜리']","['소금', '후추', '올리브유']",['닭가슴살']
freq,1,7,1,3,5,1,1,2

In [133]:
import pandas as pd

# Recipe와 User 정보를 균등하게 결합하여 JSON 형식으로 변환
def create_combined_dataset(recipeinfo_df, userinfo_df):
    combined_data = []
    len_userinfo = len(userinfo_df)  # UserInfo 데이터 수
    
    for idx, recipe_row in recipeinfo_df.iterrows():
        user_idx = idx % len_userinfo  # user_info를 균등하게 분배하기 위한 인덱스
        user_row = userinfo_df.iloc[user_idx]
        
        combined_entry = {
            "user_info": {
                "user_allergy_ingredients": eval(user_row["user_allergy_ingredients"]),
                "user_dislike_ingredients": eval(user_row["user_dislike_ingredients"]),
                "user_spicy_level": user_row["user_spicy_level"],
                "user_cooking_level": user_row["user_cooking_level"],
                "user_owned_ingredients": eval(user_row["user_owned_ingredients"]),
                "user_basic_seasoning": eval(user_row["user_basic_seasoning"]),
                "must_use_ingredients": eval(user_row["must_use_ingredients"]),
            },
            "recipe_info": {
                "_id": recipe_row["_id"],
                "title": recipe_row["title"],
                "type_key": recipe_row["type_key"],
                "method_key": recipe_row["method_key"],
                "servings": recipe_row["servings"],
                "cooking_time": recipe_row["cooking_time"] if not pd.isna(recipe_row["cooking_time"]) else "",
                "difficulty": recipe_row["difficulty"] if not pd.isna(recipe_row["difficulty"]) else "",
                "ingredients": eval(recipe_row["ingredients"]),
                "cooking_steps": eval(recipe_row["cooking_steps"]),
                "tips": eval(recipe_row["tips"]),
            },
        }
        combined_data.append(combined_entry)
    
    return combined_data

# 데이터셋 생성
combined_dataset = create_combined_dataset(df_recipeinfo, df_userinfo)

# JSON 데이터셋 저장 (옵션)
import json
with open('data/combined_dataset.json', 'w', encoding='utf-8') as f:
    json.dump(combined_dataset, f, ensure_ascii=False, indent=4)

print("데이터셋 생성 완료. 첫 번째 데이터:")
print(combined_dataset[0])
print("갯수:", len(combined_dataset))

데이터셋 생성 완료. 첫 번째 데이터:
{'user_info': {'user_allergy_ingredients': [], 'user_dislike_ingredients': [], 'user_spicy_level': '3단계', 'user_cooking_level': '중급', 'user_owned_ingredients': ['닭가슴살', '두부', '브로콜리'], 'user_basic_seasoning': ['소금', '후추', '올리브유'], 'must_use_ingredients': ['닭가슴살']}, 'recipe_info': {'_id': '67610699846f9e5eb975e532', 'title': '연어샐러드', 'type_key': '샐러드', 'method_key': '회', 'servings': '1인분', 'cooking_time': '', 'difficulty': '', 'ingredients': ['연어(150g)', '레몬(1/4개)', '발사믹식초(50g)', '어린잎채소(30g)', '후춧가루(0.01g)', '올리브오일(20g)'], 'cooking_steps': ['1. 연어는 깍둑썰기한다.', '2. 썰어 놓은 연어는 후춧가루와 레몬으로 마리네이드한다.', '3. 어린잎은 찬물에 담궈둔다.', '4. 담궈 놓은 어린잎을 체에 받쳐 물기를 뺀다.', '5. 레몬과 올리브오일을 섞는다.', '6. ?번에 발사믹소스를 넣고 연어 샐러드 양념을 만들고, 접시에 연어와 물기를 뺀 어린잎을 담는다.'], 'tips': ['발사믹소스에 레몬과 올리브오일을 섞어 별도의 소금을 넣지 않을 수 있어요.']}}
갯수: 35

In [1]:
import pandas as pd

# JSON 파일 경로
file_path = 'data/combined_dataset.json'

# JSON 파일을 DataFrame으로 불러오기
df = pd.read_json(file_path)

for i in range(len(df)):
    print(df.user_info[i])

{'user_allergy_ingredients': [], 'user_dislike_ingredients': [], 'user_spicy_level': '3단계', 'user_cooking_level': '중급', 'user_owned_ingredients': ['닭가슴살', '두부', '브로콜리'], 'user_basic_seasoning': ['소금', '후추', '올리브유'], 'must_use_ingredients': ['닭가슴살']}
{'user_allergy_ingredients': [], 'user_dislike_ingredients': ['토마토', '오이'], 'user_spicy_level': '2단계', 'user_cooking_level': '초급', 'user_owned_ingredients': ['계란', '감자', '스팸'], 'user_basic_seasoning': ['간장', '설탕', '후추'], 'must_use_ingredients': ['계란']}
{'user_allergy_ingredients': [], 'user_dislike_ingredients': ['고수'], 'user_spicy_level': '4단계', 'user_cooking_level': '고급', 'user_owned_ingredients': ['버섯', '파스타면', '레몬'], 'user_basic_seasoning': ['올리브유', '소금', '파프리카 가루'], 'must_use_ingredients': ['버섯']}
{'user_allergy_ingredients': [], 'user_dislike_ingredients': ['치즈'], 'user_spicy_level': '3단계', 'user_cooking_level': '초급', 'user_owned_ingredients': ['양파', '라면', '김치'], 'user_basic_seasoning': ['소금', '고춧가루', '간장'], 'must_use_ingredients': ['김치']}
{'user_allergy_ingredients': ['우유', '견과류'], 'user_dislike_ingredients': ['청양고추', '불닭소스'], 'user_spicy_level': '1단계', 'user_cooking_level': '중급', 'user_owned_ingredients': ['애호박', '소고기', '쌀'], 'user_basic_seasoning': ['간장', '다진 마늘', '참기름'], 'must_use_ingredients': ['소고기']}
{'user_allergy_ingredients': [], 'user_dislike_ingredients': ['돈가스', '치킨 너겟', '감자튀김', '고로케', '새우튀김'], 'user_spicy_level': '2단계', 'user_cooking_level': '초급', 'user_owned_ingredients': ['닭가슴살', '단호박', '아보카도'], 'user_basic_seasoning': ['후추', '올리브유', '발사믹 식초'], 'must_use_ingredients': ['닭가슴살']}
{'user_allergy_ingredients': [], 'user_dislike_ingredients': ['생선'], 'user_spicy_level': '3단계', 'user_cooking_level': '초급', 'user_owned_ingredients': ['계란', '밥', '햄'], 'user_basic_seasoning': ['소금', '간장', '후추'], 'must_use_ingredients': ['계란']}
{'user_allergy_ingredients': ['우유', '크림', '버터'], 'user_dislike_ingredients': ['소고기', '양고기'], 'user_spicy_level': '4단계', 'user_cooking_level': '중급', 'user_owned_ingredients': ['양파', '새우', '파스타면', '방울토마토', '바질'], 'user_basic_seasoning': ['허브솔트', '올리브유', '레몬즙', '후추', '바질페스토'], 'must_use_ingredients': ['새우']}
{'user_allergy_ingredients': [], 'user_dislike_ingredients': ['청양고추', '고추장', '고춧가루', '불닭소스', '매운 카레'], 'user_spicy_level': '1단계', 'user_cooking_level': '초급', 'user_owned_ingredients': ['연어', '브로콜리', '현미'], 'user_basic_seasoning': ['저염간장', '올리브유', '레몬즙'], 'must_use_ingredients': ['연어']}
{'user_allergy_ingredients': ['새우', '게', '견과류'], 'user_dislike_ingredients': ['닭고기', '브로콜리', '오이'], 'user_spicy_level': '5단계', 'user_cooking_level': '고급', 'user_owned_ingredients': ['연어', '아스파라거스', '파스타면'], 'user_basic_seasoning': ['버터', '허브솔트', '파마산 치즈'], 'must_use_ingredients': ['아스파라거스']}
{'user_allergy_ingredients': [], 'user_dislike_ingredients': [], 'user_spicy_level': '3단계', 'user_cooking_level': '중급', 'user_owned_ingredients': ['닭가슴살', '두부', '브로콜리'], 'user_basic_seasoning': ['소금', '후추', '올리브유'], 'must_use_ingredients': ['닭가슴살']}
{'user_allergy_ingredients': [], 'user_dislike_ingredients': ['토마토', '오이'], 'user_spicy_level': '2단계', 'user_cooking_level': '초급', 'user_owned_ingredients': ['계란', '감자', '스팸'], 'user_basic_seasoning': ['간장', '설탕', '후추'], 'must_use_ingredients': ['계란']}
{'user_allergy_ingredients': [], 'user_dislike_ingredients': ['고수'], 'user_spicy_level': '4단계', 'user_cooking_level': '고급', 'user_owned_ingredients': ['버섯', '파스타면', '레몬'], 'user_basic_seasoning': ['올리브유', '소금', '파프리카 가루'], 'must_use_ingredients': ['버섯']}
{'user_allergy_ingredients': [], 'user_dislike_ingredients': ['치즈'], 'user_spicy_level': '3단계', 'user_cooking_level': '초급', 'user_owned_ingredients': ['양파', '라면', '김치'], 'user_basic_seasoning': ['소금', '고춧가루', '간장'], 'must_use_ingredients': ['김치']}
{'user_allergy_ingredients': ['우유', '견과류'], 'user_dislike_ingredients': ['청양고추', '불닭소스'], 'user_spicy_level': '1단계', 'user_cooking_level': '중급', 'user_owned_ingredients': ['애호박', '소고기', '쌀'], 'user_basic_seasoning': ['간장', '다진 마늘', '참기름'], 'must_use_ingredients': ['소고기']}
{'user_allergy_ingredients': [], 'user_dislike_ingredients': ['돈가스', '치킨 너겟', '감자튀김', '고로케', '새우튀김'], 'user_spicy_level': '2단계', 'user_cooking_level': '초급', 'user_owned_ingredients': ['닭가슴살', '단호박', '아보카도'], 'user_basic_seasoning': ['후추', '올리브유', '발사믹 식초'], 'must_use_ingredients': ['닭가슴살']}
{'user_allergy_ingredients': [], 'user_dislike_ingredients': ['생선'], 'user_spicy_level': '3단계', 'user_cooking_level': '초급', 'user_owned_ingredients': ['계란', '밥', '햄'], 'user_basic_seasoning': ['소금', '간장', '후추'], 'must_use_ingredients': ['계란']}
{'user_allergy_ingredients': ['우유', '크림', '버터'], 'user_dislike_ingredients': ['소고기', '양고기'], 'user_spicy_level': '4단계', 'user_cooking_level': '중급', 'user_owned_ingredients': ['양파', '새우', '파스타면', '방울토마토', '바질'], 'user_basic_seasoning': ['허브솔트', '올리브유', '레몬즙', '후추', '바질페스토'], 'must_use_ingredients': ['새우']}
{'user_allergy_ingredients': [], 'user_dislike_ingredients': ['청양고추', '고추장', '고춧가루', '불닭소스', '매운 카레'], 'user_spicy_level': '1단계', 'user_cooking_level': '초급', 'user_owned_ingredients': ['연어', '브로콜리', '현미'], 'user_basic_seasoning': ['저염간장', '올리브유', '레몬즙'], 'must_use_ingredients': ['연어']}
{'user_allergy_ingredients': ['새우', '게', '견과류'], 'user_dislike_ingredients': ['닭고기', '브로콜리', '오이'], 'user_spicy_level': '5단계', 'user_cooking_level': '고급', 'user_owned_ingredients': ['연어', '아스파라거스', '파스타면'], 'user_basic_seasoning': ['버터', '허브솔트', '파마산 치즈'], 'must_use_ingredients': ['아스파라거스']}
{'user_allergy_ingredients': [], 'user_dislike_ingredients': [], 'user_spicy_level': '3단계', 'user_cooking_level': '중급', 'user_owned_ingredients': ['닭가슴살', '두부', '브로콜리'], 'user_basic_seasoning': ['소금', '후추', '올리브유'], 'must_use_ingredients': ['닭가슴살']}
{'user_allergy_ingredients': [], 'user_dislike_ingredients': ['토마토', '오이'], 'user_spicy_level': '2단계', 'user_cooking_level': '초급', 'user_owned_ingredients': ['계란', '감자', '스팸'], 'user_basic_seasoning': ['간장', '설탕', '후추'], 'must_use_ingredients': ['계란']}
{'user_allergy_ingredients': [], 'user_dislike_ingredients': ['고수'], 'user_spicy_level': '4단계', 'user_cooking_level': '고급', 'user_owned_ingredients': ['버섯', '파스타면', '레몬'], 'user_basic_seasoning': ['올리브유', '소금', '파프리카 가루'], 'must_use_ingredients': ['버섯']}
{'user_allergy_ingredients': [], 'user_dislike_ingredients': ['치즈'], 'user_spicy_level': '3단계', 'user_cooking_level': '초급', 'user_owned_ingredients': ['양파', '라면', '김치'], 'user_basic_seasoning': ['소금', '고춧가루', '간장'], 'must_use_ingredients': ['김치']}
{'user_allergy_ingredients': ['우유', '견과류'], 'user_dislike_ingredients': ['청양고추', '불닭소스'], 'user_spicy_level': '1단계', 'user_cooking_level': '중급', 'user_owned_ingredients': ['애호박', '소고기', '쌀'], 'user_basic_seasoning': ['간장', '다진 마늘', '참기름'], 'must_use_ingredients': ['소고기']}
{'user_allergy_ingredients': [], 'user_dislike_ingredients': ['돈가스', '치킨 너겟', '감자튀김', '고로케', '새우튀김'], 'user_spicy_level': '2단계', 'user_cooking_level': '초급', 'user_owned_ingredients': ['닭가슴살', '단호박', '아보카도'], 'user_basic_seasoning': ['후추', '올리브유', '발사믹 식초'], 'must_use_ingredients': ['닭가슴살']}
{'user_allergy_ingredients': [], 'user_dislike_ingredients': ['생선'], 'user_spicy_level': '3단계', 'user_cooking_level': '초급', 'user_owned_ingredients': ['계란', '밥', '햄'], 'user_basic_seasoning': ['소금', '간장', '후추'], 'must_use_ingredients': ['계란']}
{'user_allergy_ingredients': ['우유', '크림', '버터'], 'user_dislike_ingredients': ['소고기', '양고기'], 'user_spicy_level': '4단계', 'user_cooking_level': '중급', 'user_owned_ingredients': ['양파', '새우', '파스타면', '방울토마토', '바질'], 'user_basic_seasoning': ['허브솔트', '올리브유', '레몬즙', '후추', '바질페스토'], 'must_use_ingredients': ['새우']}
{'user_allergy_ingredients': [], 'user_dislike_ingredients': ['청양고추', '고추장', '고춧가루', '불닭소스', '매운 카레'], 'user_spicy_level': '1단계', 'user_cooking_level': '초급', 'user_owned_ingredients': ['연어', '브로콜리', '현미'], 'user_basic_seasoning': ['저염간장', '올리브유', '레몬즙'], 'must_use_ingredients': ['연어']}
{'user_allergy_ingredients': ['새우', '게', '견과류'], 'user_dislike_ingredients': ['닭고기', '브로콜리', '오이'], 'user_spicy_level': '5단계', 'user_cooking_level': '고급', 'user_owned_ingredients': ['연어', '아스파라거스', '파스타면'], 'user_basic_seasoning': ['버터', '허브솔트', '파마산 치즈'], 'must_use_ingredients': ['아스파라거스']}
{'user_allergy_ingredients': [], 'user_dislike_ingredients': [], 'user_spicy_level': '3단계', 'user_cooking_level': '중급', 'user_owned_ingredients': ['닭가슴살', '두부', '브로콜리'], 'user_basic_seasoning': ['소금', '후추', '올리브유'], 'must_use_ingredients': ['닭가슴살']}
{'user_allergy_ingredients': [], 'user_dislike_ingredients': ['토마토', '오이'], 'user_spicy_level': '2단계', 'user_cooking_level': '초급', 'user_owned_ingredients': ['계란', '감자', '스팸'], 'user_basic_seasoning': ['간장', '설탕', '후추'], 'must_use_ingredients': ['계란']}
{'user_allergy_ingredients': [], 'user_dislike_ingredients': ['고수'], 'user_spicy_level': '4단계', 'user_cooking_level': '고급', 'user_owned_ingredients': ['버섯', '파스타면', '레몬'], 'user_basic_seasoning': ['올리브유', '소금', '파프리카 가루'], 'must_use_ingredients': ['버섯']}
{'user_allergy_ingredients': [], 'user_dislike_ingredients': ['치즈'], 'user_spicy_level': '3단계', 'user_cooking_level': '초급', 'user_owned_ingredients': ['양파', '라면', '김치'], 'user_basic_seasoning': ['소금', '고춧가루', '간장'], 'must_use_ingredients': ['김치']}
{'user_allergy_ingredients': ['우유', '견과류'], 'user_dislike_ingredients': ['청양고추', '불닭소스'], 'user_spicy_level': '1단계', 'user_cooking_level': '중급', 'user_owned_ingredients': ['애호박', '소고기', '쌀'], 'user_basic_seasoning': ['간장', '다진 마늘', '참기름'], 'must_use_ingredients': ['소고기']}

## 작은 datatset 생성

In [2]:
df[:1]

,user_info,recipe_info
0,"{'user_allergy_ingredients': [], 'user_dislike...","{'_id': '67610699846f9e5eb975e532', 'title': '..."

In [ ]:
import json
with open('data/small_combined_dataset.json', 'w', encoding='utf-8') as f:
    json.dump(combined_dataset[:2], f, ensure_ascii=False, indent=4)

### dataset에 find_keyIngredients_tasty 결과 추가

## llm 기능 실행

In [3]:
from langchain_teddynote import logging
# set_enable=False 로 지정하면 추적을 하지 않습니다.
logging.langsmith("랭체인 튜토리얼 프로젝트", set_enable=False)

LangSmith 추적을 하지 않습니다.

## 3개 행으로 연습

In [9]:
import sys
import pandas as pd
sys.path.append('../')  # 상위 디렉토리의 src 폴더를 경로에 추가
from src.recipe_change_origin import generate_recipe

df = pd.read_json('data/combined_dataset.json')
df_cp = df[:3].copy().reset_index(drop=True)

df_cp['generation'] = None  # 열 초기화

for i in range(len(df_cp)):
    df_cp.at[i, 'generation'] = await generate_recipe(df_cp.iloc[i].recipe_info, df.iloc[i].user_info, 1)

df_cp

2024-12-23 00:22:35,114 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 00:22:35,115 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 00:22:35,120 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 00:22:35,121 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 00:22:35,122 - recipe_logger - INFO - LLM 레시피 생성 중...
2024-12-23 00:22:54,044 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 00:22:54,061 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 00:22:54,062 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 00:22:54,063 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 00:22:54,065 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 00:22:54,066 - recipe_logger - INFO - LLM 레시피 생성 중...
2024-12-23 00:23:15,890 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 00:23:15,905 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 00:23:15,906 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 00:23:15,907 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 00:23:15,908 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 00:23:15,908 - recipe_logger - INFO - LLM 레시피 생성 중...
2024-12-23 00:23:33,256 - recipe_logger - INFO - LLM 레시피 생성 완료

,user_info,recipe_info,generation
0,"{'user_allergy_ingredients': [], 'user_dislike...","{'_id': '67610699846f9e5eb975e532', 'title': '...",{'main_changes_from_original_recipe': ['연어를 닭가...
1,"{'user_allergy_ingredients': [], 'user_dislike...","{'_id': '6761069a846f9e5eb9761021', 'title': '...",{'main_changes_from_original_recipe': ['🍇 포도주스...
2,"{'user_allergy_ingredients': [], 'user_dislike...","{'_id': '6761069a846f9e5eb9760836', 'title': '...",{'main_changes_from_original_recipe': ['🥣 양파와 ...

## 실제로 데이터 만들기 - gpt-4o-mini

In [4]:
from langchain_teddynote import logging
# set_enable=False 로 지정하면 추적을 하지 않습니다.
logging.langsmith("랭체인 튜토리얼 프로젝트", set_enable=False)

LangSmith 추적을 하지 않습니다.

In [1]:
import nest_asyncio
import asyncio
import pandas as pd
import sys
sys.path.append('../')  # 상위 디렉토리의 src 폴더를 경로에 추가
from src.recipe_change_origin import generate_recipe

# nest_asyncio로 이미 실행 중인 루프에서 중첩 실행 허용
nest_asyncio.apply()

# 동시 요청 제한과 재시도 설정
MAX_CONCURRENT_REQUESTS = 3
RETRY_LIMIT = 3

# 데이터 로드
df = pd.read_json('data/combined_dataset.json')

async def generate(df, feature_num):
    df['generation'] = None  # 결과 저장 열 생성

    # Semaphore 생성
    semaphore = asyncio.Semaphore(MAX_CONCURRENT_REQUESTS)

    tasks = []  # 모든 작업을 저장할 리스트

    for i in range(len(df)):
        retry_count = 0
        while retry_count <= RETRY_LIMIT:
            try:
                # Semaphore로 동시 요청 제한
                async with semaphore:
                    print(f"Processing row {i} (Attempt {retry_count + 1})...")
                    result = await generate_recipe(df.iloc[i].recipe_info, df.iloc[i].user_info, feature_num)
                    df.at[i, 'generation'] = result  # 결과 저장
                    break  # 성공하면 반복문 종료
            except Exception as e:
                retry_count += 1
                if retry_count > RETRY_LIMIT:
                    print(f"Failed to process row {i} after {RETRY_LIMIT} retries.")
                    break  # 재시도 초과 시 반복문 종료
                print(f"Error processing row {i}: {e}. Retrying...")
                await asyncio.sleep(10 ** retry_count)  # 재시도 전 대기

        tasks.append(asyncio.sleep(0))  # 리스트에 임시 작업 추가 (추후 확장 가능)

    await asyncio.gather(*tasks)  # 모든 작업 실행

    # 결과 확인
    print(df.head())

2024-12-23 02:04:30,363 - recipe_logger - INFO - LLM 초기화 완료: gpt-4o-mini

In [15]:
feature_num = 1  # 사용할 feature_num 설정

# 이벤트 루프 생성 및 실행
loop = asyncio.get_event_loop()
loop.run_until_complete(generate(df, feature_num))

# 결과 저장
output_file = f'groundTruth_f{feature_num}.csv'
df.to_csv(output_file, index=False, encoding='utf-8-sig')
print(f"Processed data saved to {output_file}")

2024-12-23 00:58:19,221 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 00:58:19,222 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 00:58:19,226 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 00:58:19,227 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 00:58:19,228 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 0 (Attempt 1)...

2024-12-23 00:58:36,786 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 00:58:36,799 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 00:58:36,799 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 00:58:36,800 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 00:58:36,801 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 00:58:36,802 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 1 (Attempt 1)...

2024-12-23 00:58:58,465 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 00:58:58,481 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 00:58:58,482 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 00:58:58,482 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 00:58:58,483 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 00:58:58,484 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 2 (Attempt 1)...

2024-12-23 00:59:19,200 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 00:59:19,213 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 00:59:19,213 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 00:59:19,214 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 00:59:19,215 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 00:59:19,215 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 3 (Attempt 1)...

2024-12-23 00:59:37,120 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 00:59:37,135 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 00:59:37,135 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 00:59:37,136 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 00:59:37,137 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 00:59:37,138 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 4 (Attempt 1)...

2024-12-23 01:00:03,002 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:00:03,020 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:00:03,021 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:00:03,022 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:00:03,023 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:00:03,024 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 5 (Attempt 1)...

2024-12-23 01:00:22,039 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:00:22,065 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:00:22,066 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:00:22,067 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:00:22,067 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:00:22,068 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 6 (Attempt 1)...

2024-12-23 01:00:44,295 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:00:44,309 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:00:44,310 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:00:44,310 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:00:44,311 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:00:44,312 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 7 (Attempt 1)...

2024-12-23 01:01:02,293 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:01:02,311 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:01:02,312 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:01:02,313 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:01:02,314 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:01:02,314 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 8 (Attempt 1)...

2024-12-23 01:01:19,420 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:01:19,434 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:01:19,434 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:01:19,435 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:01:19,436 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:01:19,436 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 9 (Attempt 1)...

2024-12-23 01:01:40,360 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:01:40,373 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:01:40,373 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:01:40,374 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:01:40,375 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:01:40,375 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 10 (Attempt 1)...

2024-12-23 01:01:56,690 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:01:56,705 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:01:56,706 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:01:56,707 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:01:56,707 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:01:56,708 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 11 (Attempt 1)...

2024-12-23 01:02:34,666 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:02:34,682 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:02:34,683 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:02:34,683 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:02:34,684 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:02:34,685 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 12 (Attempt 1)...

2024-12-23 01:02:49,331 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:02:49,344 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:02:49,344 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:02:49,345 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:02:49,345 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:02:49,346 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 13 (Attempt 1)...

2024-12-23 01:03:02,160 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:03:02,172 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:03:02,173 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:03:02,174 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:03:02,175 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:03:02,177 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 14 (Attempt 1)...

2024-12-23 01:03:16,469 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:03:16,482 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:03:16,482 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:03:16,483 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:03:16,483 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:03:16,484 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 15 (Attempt 1)...

2024-12-23 01:03:31,319 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:03:31,331 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:03:31,331 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:03:31,332 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:03:31,333 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:03:31,334 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 16 (Attempt 1)...

2024-12-23 01:03:48,212 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:03:48,224 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:03:48,225 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:03:48,226 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:03:48,227 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:03:48,228 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 17 (Attempt 1)...

2024-12-23 01:04:00,295 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:04:00,309 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:04:00,309 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:04:00,310 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:04:00,310 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:04:00,311 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 18 (Attempt 1)...

2024-12-23 01:04:14,737 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:04:14,750 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:04:14,751 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:04:14,751 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:04:14,752 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:04:14,753 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 19 (Attempt 1)...

2024-12-23 01:04:40,034 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:04:40,047 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:04:40,047 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:04:40,048 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:04:40,049 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:04:40,049 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 20 (Attempt 1)...

2024-12-23 01:05:02,151 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:05:02,164 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:05:02,164 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:05:02,165 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:05:02,165 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:05:02,166 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 21 (Attempt 1)...

2024-12-23 01:05:16,149 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:05:16,161 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:05:16,162 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:05:16,162 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:05:16,163 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:05:16,164 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 22 (Attempt 1)...

2024-12-23 01:05:29,676 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:05:29,688 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:05:29,688 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:05:29,689 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:05:29,690 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:05:29,691 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 23 (Attempt 1)...

2024-12-23 01:05:44,848 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:05:44,860 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:05:44,861 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:05:44,862 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:05:44,862 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:05:44,863 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 24 (Attempt 1)...

2024-12-23 01:05:59,915 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:05:59,930 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:05:59,931 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:05:59,932 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:05:59,933 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:05:59,934 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 25 (Attempt 1)...

2024-12-23 01:06:15,165 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:06:15,178 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:06:15,178 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:06:15,179 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:06:15,180 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:06:15,181 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 26 (Attempt 1)...

2024-12-23 01:06:28,979 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:06:28,993 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:06:28,993 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:06:28,994 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:06:28,994 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:06:28,995 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 27 (Attempt 1)...

2024-12-23 01:06:44,710 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:06:44,726 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:06:44,727 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:06:44,728 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:06:44,729 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:06:44,730 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 28 (Attempt 1)...

2024-12-23 01:06:57,144 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:06:57,156 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:06:57,156 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:06:57,157 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:06:57,157 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:06:57,158 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 29 (Attempt 1)...

2024-12-23 01:07:09,429 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:07:09,441 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:07:09,441 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:07:09,442 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:07:09,442 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:07:09,443 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 30 (Attempt 1)...

2024-12-23 01:07:24,175 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:07:24,186 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:07:24,187 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:07:24,188 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:07:24,189 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:07:24,189 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 31 (Attempt 1)...

2024-12-23 01:07:37,196 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:07:37,210 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:07:37,211 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:07:37,212 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:07:37,212 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:07:37,213 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 32 (Attempt 1)...

2024-12-23 01:07:52,127 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:07:52,142 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:07:52,142 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:07:52,143 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:07:52,144 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:07:52,145 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 33 (Attempt 1)...

2024-12-23 01:08:06,192 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:08:06,205 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:08:06,205 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:08:06,206 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:08:06,208 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:08:06,209 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 34 (Attempt 1)...

2024-12-23 01:08:26,355 - recipe_logger - INFO - LLM 레시피 생성 완료

                                           user_info  \
0  {'user_allergy_ingredients': [], 'user_dislike...
1  {'user_allergy_ingredients': [], 'user_dislike...
2  {'user_allergy_ingredients': [], 'user_dislike...
3  {'user_allergy_ingredients': [], 'user_dislike...
4  {'user_allergy_ingredients': ['우유', '견과류'], 'u...

                                         recipe_info  \
0  {'_id': '67610699846f9e5eb975e532', 'title': '...
1  {'_id': '6761069a846f9e5eb9761021', 'title': '...
2  {'_id': '6761069a846f9e5eb9760836', 'title': '...
3  {'_id': '6761069a846f9e5eb9760639', 'title': '...
4  {'_id': '6761069a846f9e5eb976093b', 'title': '...

                                          generation
0  {'main_changes_from_original_recipe': ['🥗 닭가슴살...
1  {'main_changes_from_original_recipe': ['🍇 포도주스...
2  {'main_changes_from_original_recipe': ['🥣 양파는 ...
3  {'main_changes_from_original_recipe': ['🍋 레몬을 ...
4  {'main_changes_from_original_recipe': ['🥣 황태채 ...
Processed data saved to groundTruth_f1.csv

In [16]:
feature_num = 2  # 사용할 feature_num 설정

# 이벤트 루프 생성 및 실행
loop = asyncio.get_event_loop()
loop.run_until_complete(generate(df, feature_num))

# 결과 저장
output_file = f'data/groundTruth/groundTruth_f{feature_num}.csv'
df.to_csv(output_file, index=False, encoding='utf-8-sig')
print(f"Processed data saved to {output_file}")

2024-12-23 01:08:26,403 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:08:26,404 - recipe_logger - INFO - langfuse prompt template 생성 완료

Processing row 0 (Attempt 1)...

2024-12-23 01:08:26,632 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:08:26,633 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:08:26,635 - recipe_logger - INFO - LLM 레시피 생성 중...
2024-12-23 01:08:41,887 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:08:41,904 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:08:41,905 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:08:41,906 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:08:41,907 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:08:41,908 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 1 (Attempt 1)...

2024-12-23 01:08:57,318 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:08:57,334 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:08:57,334 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:08:57,335 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:08:57,336 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:08:57,338 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 2 (Attempt 1)...

2024-12-23 01:09:12,721 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:09:12,733 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:09:12,733 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:09:12,734 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:09:12,735 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:09:12,736 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 3 (Attempt 1)...

2024-12-23 01:09:25,928 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:09:25,942 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:09:25,942 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:09:25,943 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:09:25,944 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:09:25,944 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 4 (Attempt 1)...

2024-12-23 01:09:44,566 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:09:44,579 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:09:44,579 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:09:44,580 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:09:44,581 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:09:44,581 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 5 (Attempt 1)...

2024-12-23 01:09:56,956 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:09:56,971 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:09:56,972 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:09:56,973 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:09:56,974 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:09:56,974 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 6 (Attempt 1)...

2024-12-23 01:10:15,202 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:10:15,215 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:10:15,216 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:10:15,217 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:10:15,217 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:10:15,218 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 7 (Attempt 1)...

2024-12-23 01:10:30,853 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:10:30,868 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:10:30,868 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:10:30,869 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:10:30,869 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:10:30,870 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 8 (Attempt 1)...

2024-12-23 01:10:44,872 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:10:44,888 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:10:44,889 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:10:44,890 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:10:44,891 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:10:44,892 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 9 (Attempt 1)...

2024-12-23 01:11:00,135 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:11:00,147 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:11:00,147 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:11:00,148 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:11:00,149 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:11:00,149 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 10 (Attempt 1)...

2024-12-23 01:11:13,338 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:11:13,351 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:11:13,351 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:11:13,352 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:11:13,353 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:11:13,354 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 11 (Attempt 1)...

2024-12-23 01:11:33,931 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:11:33,946 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:11:33,946 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:11:33,947 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:11:33,948 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:11:33,948 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 12 (Attempt 1)...

2024-12-23 01:11:49,594 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:11:49,609 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:11:49,610 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:11:49,611 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:11:49,611 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:11:49,612 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 13 (Attempt 1)...

2024-12-23 01:12:06,295 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:12:06,310 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:12:06,310 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:12:06,311 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:12:06,312 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:12:06,313 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 14 (Attempt 1)...

2024-12-23 01:12:25,439 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:12:25,457 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:12:25,458 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:12:25,459 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:12:25,460 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:12:25,461 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 15 (Attempt 1)...

2024-12-23 01:12:48,074 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:12:48,086 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:12:48,086 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:12:48,087 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:12:48,088 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:12:48,089 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 16 (Attempt 1)...

2024-12-23 01:13:05,169 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:13:05,185 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:13:05,185 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:13:05,186 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:13:05,186 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:13:05,187 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 17 (Attempt 1)...

2024-12-23 01:13:20,476 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:13:20,489 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:13:20,489 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:13:20,490 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:13:20,491 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:13:20,492 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 18 (Attempt 1)...

2024-12-23 01:13:40,951 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:13:40,967 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:13:40,968 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:13:40,969 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:13:40,970 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:13:40,971 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 19 (Attempt 1)...

2024-12-23 01:14:03,746 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:14:03,758 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:14:03,758 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:14:03,760 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:14:03,760 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:14:03,761 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 20 (Attempt 1)...

2024-12-23 01:14:25,552 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:14:25,568 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:14:25,568 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:14:25,569 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:14:25,570 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:14:25,570 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 21 (Attempt 1)...

2024-12-23 01:14:40,795 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:14:40,808 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:14:40,808 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:14:40,809 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:14:40,810 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:14:40,811 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 22 (Attempt 1)...

2024-12-23 01:14:50,642 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:14:50,657 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:14:50,658 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:14:50,659 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:14:50,660 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:14:50,660 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 23 (Attempt 1)...

2024-12-23 01:15:18,056 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:15:18,069 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:15:18,069 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:15:18,070 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:15:18,071 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:15:18,072 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 24 (Attempt 1)...

2024-12-23 01:15:35,970 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:15:35,983 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:15:35,983 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:15:35,984 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:15:35,986 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:15:35,987 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 25 (Attempt 1)...

2024-12-23 01:15:56,643 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:15:56,657 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:15:56,658 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:15:56,659 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:15:56,659 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:15:56,660 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 26 (Attempt 1)...

2024-12-23 01:16:13,064 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:16:13,076 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:16:13,077 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:16:13,077 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:16:13,078 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:16:13,079 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 27 (Attempt 1)...

2024-12-23 01:16:31,920 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:16:31,935 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:16:31,936 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:16:31,936 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:16:31,937 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:16:31,938 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 28 (Attempt 1)...

2024-12-23 01:16:50,039 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:16:50,052 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:16:50,052 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:16:50,053 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:16:50,054 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:16:50,055 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 29 (Attempt 1)...

2024-12-23 01:17:03,749 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:17:03,762 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:17:03,763 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:17:03,763 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:17:03,764 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:17:03,765 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 30 (Attempt 1)...

2024-12-23 01:17:24,728 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:17:24,741 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:17:24,741 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:17:24,742 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:17:24,743 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:17:24,744 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 31 (Attempt 1)...

2024-12-23 01:17:44,223 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:17:44,238 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:17:44,239 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:17:44,239 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:17:44,240 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:17:44,241 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 32 (Attempt 1)...

2024-12-23 01:18:04,133 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:18:04,150 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:18:04,151 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:18:04,152 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:18:04,152 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:18:04,153 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 33 (Attempt 1)...

2024-12-23 01:18:25,574 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:18:25,589 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:18:25,590 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:18:25,590 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:18:25,591 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:18:25,592 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 34 (Attempt 1)...

2024-12-23 01:18:48,963 - recipe_logger - INFO - LLM 레시피 생성 완료

                                           user_info  \
0  {'user_allergy_ingredients': [], 'user_dislike...
1  {'user_allergy_ingredients': [], 'user_dislike...
2  {'user_allergy_ingredients': [], 'user_dislike...
3  {'user_allergy_ingredients': [], 'user_dislike...
4  {'user_allergy_ingredients': ['우유', '견과류'], 'u...

                                         recipe_info  \
0  {'_id': '67610699846f9e5eb975e532', 'title': '...
1  {'_id': '6761069a846f9e5eb9761021', 'title': '...
2  {'_id': '6761069a846f9e5eb9760836', 'title': '...
3  {'_id': '6761069a846f9e5eb9760639', 'title': '...
4  {'_id': '6761069a846f9e5eb976093b', 'title': '...

                                          generation
0  {'main_changes_from_original_recipe': ['연어 대신 ...
1  {'main_changes_from_original_recipe': ['🍇 포도주스...
2  {'main_changes_from_original_recipe': ['양파와 감자...
3  {'main_changes_from_original_recipe': ['레몬을 굵은...
4  {'main_changes_from_original_recipe': ['소고기를 황...
Processed data saved to data/groundTruth/groundTruth_f2.csv

In [5]:
feature_num = 3  # 사용할 feature_num 설정

# 이벤트 루프 생성 및 실행
loop = asyncio.get_event_loop()
loop.run_until_complete(generate(df, feature_num))

# 결과 저장
output_file = f'data/groundTruth/groundTruth_f{feature_num}.csv'
df.to_csv(output_file, index=False, encoding='utf-8-sig')
print(f"Processed data saved to {output_file}")

2024-12-23 02:05:32,392 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:05:32,394 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:05:32,397 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:05:32,399 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:05:32,401 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:05:32,402 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 0 (Attempt 1)...

2024-12-23 02:06:02,258 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:06:02,270 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:06:02,270 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:06:02,271 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:06:02,272 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:06:02,272 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:06:02,273 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 1 (Attempt 1)...

2024-12-23 02:06:44,661 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:06:44,676 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:06:44,676 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:06:44,677 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:06:44,678 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:06:44,679 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:06:44,679 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 2 (Attempt 1)...

2024-12-23 02:07:32,263 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:07:32,276 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:07:32,277 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:07:32,278 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:07:32,278 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:07:32,279 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:07:32,280 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 3 (Attempt 1)...

2024-12-23 02:07:59,724 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:07:59,738 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:07:59,738 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:07:59,739 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:07:59,740 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:07:59,740 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:07:59,741 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 4 (Attempt 1)...

2024-12-23 02:08:44,468 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:08:44,482 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:08:44,483 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:08:44,484 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:08:44,484 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:08:44,485 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:08:44,485 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 5 (Attempt 1)...

2024-12-23 02:09:40,565 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:09:40,578 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:09:40,578 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:09:40,579 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:09:40,579 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:09:40,580 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:09:40,580 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 6 (Attempt 1)...

2024-12-23 02:10:14,541 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:10:14,563 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:10:14,563 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:10:14,565 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:10:14,566 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:10:14,567 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:10:14,568 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 7 (Attempt 1)...

2024-12-23 02:11:00,250 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:11:00,261 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:11:00,261 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:11:00,262 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:11:00,263 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:11:00,263 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:11:00,263 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 8 (Attempt 1)...

2024-12-23 02:12:15,628 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:12:15,646 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:12:15,647 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:12:15,648 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:12:15,649 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:12:15,650 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:12:15,650 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 9 (Attempt 1)...

2024-12-23 02:13:06,670 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:13:06,684 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:13:06,684 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:13:06,685 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:13:06,685 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:13:06,686 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:13:06,686 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 10 (Attempt 1)...

2024-12-23 02:13:42,042 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:13:42,057 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:13:42,057 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:13:42,058 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:13:42,059 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:13:42,060 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:13:42,060 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 11 (Attempt 1)...

2024-12-23 02:14:10,921 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:14:10,934 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:14:10,935 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:14:10,935 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:14:10,936 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:14:10,937 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:14:10,937 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 12 (Attempt 1)...

2024-12-23 02:14:37,530 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:14:37,545 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:14:37,545 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:14:37,546 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:14:37,546 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:14:37,547 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:14:37,547 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 13 (Attempt 1)...

2024-12-23 02:15:09,905 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:15:09,918 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:15:09,918 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:15:09,919 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:15:09,920 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:15:09,920 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:15:09,921 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 14 (Attempt 1)...

2024-12-23 02:15:38,544 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:15:38,560 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:15:38,561 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:15:38,562 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:15:38,563 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:15:38,564 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:15:38,565 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 15 (Attempt 1)...

2024-12-23 02:16:26,185 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:16:26,199 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:16:26,199 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:16:26,200 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:16:26,201 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:16:26,202 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:16:26,202 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 16 (Attempt 1)...

2024-12-23 02:16:59,450 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:16:59,462 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:16:59,463 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:16:59,463 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:16:59,464 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:16:59,465 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:16:59,465 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 17 (Attempt 1)...

2024-12-23 02:17:29,509 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:17:29,522 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:17:29,523 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:17:29,523 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:17:29,524 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:17:29,525 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:17:29,525 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 18 (Attempt 1)...

2024-12-23 02:18:28,356 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:18:28,372 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:18:28,372 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:18:28,373 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:18:28,374 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:18:28,374 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:18:28,375 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 19 (Attempt 1)...

2024-12-23 02:19:10,445 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:19:10,459 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:19:10,459 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:19:10,460 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:19:10,460 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:19:10,461 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:19:10,462 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 20 (Attempt 1)...

2024-12-23 02:19:59,821 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:19:59,837 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:19:59,838 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:19:59,839 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:19:59,840 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:19:59,842 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:19:59,847 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 21 (Attempt 1)...

2024-12-23 02:22:08,227 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:22:08,255 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:22:08,257 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:22:08,259 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:22:08,260 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:22:08,261 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:22:08,261 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 22 (Attempt 1)...

2024-12-23 02:22:34,563 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:22:34,577 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:22:34,578 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:22:34,578 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:22:34,579 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:22:34,580 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:22:34,580 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 23 (Attempt 1)...

2024-12-23 02:23:09,622 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:23:09,637 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:23:09,638 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:23:09,638 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:23:09,639 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:23:09,640 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:23:09,640 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 24 (Attempt 1)...

2024-12-23 02:24:41,286 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:24:41,303 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:24:41,303 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:24:41,306 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:24:41,307 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:24:41,309 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:24:41,310 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 25 (Attempt 1)...

2024-12-23 02:25:15,389 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:25:15,402 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:25:15,402 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:25:15,403 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:25:15,404 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:25:15,405 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:25:15,405 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 26 (Attempt 1)...

2024-12-23 02:25:45,209 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:25:45,225 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:25:45,225 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:25:45,226 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:25:45,227 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:25:45,228 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:25:45,228 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 27 (Attempt 1)...

2024-12-23 02:26:21,872 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:26:21,885 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:26:21,886 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:26:21,887 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:26:21,887 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:26:21,888 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:26:21,888 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 28 (Attempt 1)...

2024-12-23 02:26:51,275 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:26:51,287 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:26:51,288 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:26:51,289 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:26:51,289 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:26:51,290 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:26:51,290 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 29 (Attempt 1)...

2024-12-23 02:27:17,427 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:27:17,441 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:27:17,442 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:27:17,443 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:27:17,444 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:27:17,444 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:27:17,445 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 30 (Attempt 1)...

2024-12-23 02:27:57,406 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:27:57,417 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:27:57,418 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:27:57,419 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:27:57,419 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:27:57,420 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:27:57,420 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 31 (Attempt 1)...

2024-12-23 02:28:40,373 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:28:40,388 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:28:40,389 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:28:40,390 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:28:40,391 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:28:40,391 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:28:40,392 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 32 (Attempt 1)...

2024-12-23 02:29:15,143 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:29:15,157 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:29:15,157 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:29:15,158 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:29:15,159 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:29:15,160 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:29:15,160 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 33 (Attempt 1)...

2024-12-23 02:29:54,097 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:29:54,109 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:29:54,110 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:29:54,110 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:29:54,111 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:29:54,112 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:29:54,112 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 34 (Attempt 1)...

2024-12-23 02:30:32,559 - recipe_logger - INFO - LLM 레시피 생성 완료

                                           user_info  \
0  {'user_allergy_ingredients': [], 'user_dislike...
1  {'user_allergy_ingredients': [], 'user_dislike...
2  {'user_allergy_ingredients': [], 'user_dislike...
3  {'user_allergy_ingredients': [], 'user_dislike...
4  {'user_allergy_ingredients': ['우유', '견과류'], 'u...

                                         recipe_info  \
0  {'_id': '67610699846f9e5eb975e532', 'title': '...
1  {'_id': '6761069a846f9e5eb9761021', 'title': '...
2  {'_id': '6761069a846f9e5eb9760836', 'title': '...
3  {'_id': '6761069a846f9e5eb9760639', 'title': '...
4  {'_id': '6761069a846f9e5eb976093b', 'title': '...

                                          generation
0  {'original_recipe_food_group_composition': [{'...
1  {'original_recipe_food_group_composition': [{'...
2  {'original_recipe_food_group_composition': [{'...
3  {'original_recipe_food_group_composition': [{'...
4  {'original_recipe_food_group_composition': [{'...
Processed data saved to data/groundTruth/groundTruth_f3.csv

## 실제로 데이터 만들기 - groundTruth

In [1]:
from langchain_teddynote import logging
# set_enable=False 로 지정하면 추적을 하지 않습니다.
logging.langsmith("랭체인 튜토리얼 프로젝트", set_enable=False)

LangSmith 추적을 하지 않습니다.

In [1]:
import nest_asyncio
import asyncio
import pandas as pd
import sys
sys.path.append('../')  # 상위 디렉토리의 src 폴더를 경로에 추가
from src.recipe_change_origin import generate_recipe

# nest_asyncio로 이미 실행 중인 루프에서 중첩 실행 허용
nest_asyncio.apply()

# 동시 요청 제한과 재시도 설정
MAX_CONCURRENT_REQUESTS = 3
RETRY_LIMIT = 3

async def generate(df, feature_num):
    df['groundTruth'] = None  # 결과 저장 열 생성

    # Semaphore 생성
    semaphore = asyncio.Semaphore(MAX_CONCURRENT_REQUESTS)

    tasks = []  # 모든 작업을 저장할 리스트

    for i in range(len(df)):
        retry_count = 0
        while retry_count <= RETRY_LIMIT:
            try:
                # Semaphore로 동시 요청 제한
                async with semaphore:
                    print(f"Processing row {i} (Attempt {retry_count + 1})...")
                    result = await generate_recipe(df.iloc[i].recipe_info, df.iloc[i].user_info, feature_num)
                    df.at[i, 'groundTruth'] = result  # 결과 저장
                    break  # 성공하면 반복문 종료
            except Exception as e:
                retry_count += 1
                if retry_count > RETRY_LIMIT:
                    print(f"Failed to process row {i} after {RETRY_LIMIT} retries.")
                    break  # 재시도 초과 시 반복문 종료
                print(f"Error processing row {i}: {e}. Retrying...")
                await asyncio.sleep(10 ** retry_count)  # 재시도 전 대기

        tasks.append(asyncio.sleep(0))  # 리스트에 임시 작업 추가 (추후 확장 가능)

    await asyncio.gather(*tasks)  # 모든 작업 실행

    # 결과 확인
    print(df.head())

2024-12-23 02:34:54,275 - recipe_logger - INFO - LLM 초기화 완료: gpt-4o

In [3]:
# 데이터 로드
feature_num = 1  # 사용할 feature_num 설정

file_path = f'data/groundTruth/groundTruth_f{feature_num}.csv'
df = pd.read_csv(file_path)

# 이벤트 루프 생성 및 실행
loop = asyncio.get_event_loop()
loop.run_until_complete(generate(df, feature_num))

# 결과 저장
output_file = f'data/groundTruth/final_groundTruth_f{feature_num}.csv'
df.to_csv(output_file, index=False, encoding='utf-8-sig')
print(f"Processed data saved to {output_file}")

2024-12-23 01:41:53,218 - recipe_logger - INFO - json 출력 파서 초기화 완료.

Processing row 0 (Attempt 1)...

2024-12-23 01:41:53,775 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:41:53,949 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:41:54,124 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:41:54,125 - recipe_logger - INFO - LLM 레시피 생성 중...
2024-12-23 01:42:08,735 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:42:08,749 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:42:08,749 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:42:08,750 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:42:08,751 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:42:08,752 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 1 (Attempt 1)...

2024-12-23 01:42:22,475 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:42:22,489 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:42:22,489 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:42:22,490 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:42:22,491 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:42:22,492 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 2 (Attempt 1)...

2024-12-23 01:42:40,519 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:42:40,533 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:42:40,533 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:42:40,534 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:42:40,535 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:42:40,535 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 3 (Attempt 1)...

2024-12-23 01:42:56,496 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:42:56,513 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:42:56,514 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:42:56,515 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:42:56,516 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:42:56,517 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 4 (Attempt 1)...

2024-12-23 01:43:10,542 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:43:10,554 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:43:10,554 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:43:10,555 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:43:10,556 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:43:10,557 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 5 (Attempt 1)...

2024-12-23 01:43:21,259 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:43:21,272 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:43:21,272 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:43:21,273 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:43:21,274 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:43:21,275 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 6 (Attempt 1)...

2024-12-23 01:43:33,155 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:43:33,169 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:43:33,170 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:43:33,171 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:43:33,172 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:43:33,173 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 7 (Attempt 1)...

2024-12-23 01:43:48,894 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:43:48,910 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:43:48,911 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:43:48,912 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:43:48,913 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:43:48,914 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 8 (Attempt 1)...

2024-12-23 01:44:03,425 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:44:03,436 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:44:03,437 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:44:03,438 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:44:03,438 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:44:03,439 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 9 (Attempt 1)...

2024-12-23 01:44:16,443 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:44:16,454 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:44:16,455 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:44:16,456 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:44:16,456 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:44:16,457 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 10 (Attempt 1)...

2024-12-23 01:44:29,549 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:44:29,561 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:44:29,562 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:44:29,563 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:44:29,564 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:44:29,564 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 11 (Attempt 1)...

2024-12-23 01:44:45,121 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:44:45,136 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:44:45,136 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:44:45,137 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:44:45,138 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:44:45,139 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 12 (Attempt 1)...

2024-12-23 01:44:59,348 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:44:59,360 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:44:59,360 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:44:59,361 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:44:59,362 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:44:59,363 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 13 (Attempt 1)...

2024-12-23 01:45:13,259 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:45:13,270 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:45:13,270 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:45:13,271 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:45:13,272 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:45:13,273 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 14 (Attempt 1)...

2024-12-23 01:45:25,401 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:45:25,419 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:45:25,420 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:45:25,423 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:45:25,424 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:45:25,426 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 15 (Attempt 1)...

2024-12-23 01:45:48,670 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:45:48,683 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:45:48,683 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:45:48,684 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:45:48,685 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:45:48,686 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 16 (Attempt 1)...

2024-12-23 01:46:13,459 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:46:13,474 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:46:13,475 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:46:13,475 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:46:13,476 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:46:13,477 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 17 (Attempt 1)...

2024-12-23 01:46:29,356 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:46:29,371 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:46:29,372 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:46:29,372 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:46:29,373 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:46:29,375 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 18 (Attempt 1)...

2024-12-23 01:46:44,304 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:46:44,316 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:46:44,317 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:46:44,318 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:46:44,318 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:46:44,319 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 19 (Attempt 1)...

2024-12-23 01:47:02,027 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:47:02,041 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:47:02,042 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:47:02,044 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:47:02,044 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:47:02,045 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 20 (Attempt 1)...

2024-12-23 01:47:21,380 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:47:21,392 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:47:21,393 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:47:21,394 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:47:21,395 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:47:21,396 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 21 (Attempt 1)...

2024-12-23 01:47:35,559 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:47:35,572 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:47:35,572 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:47:35,573 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:47:35,574 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:47:35,574 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 22 (Attempt 1)...

2024-12-23 01:47:47,958 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:47:47,973 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:47:47,973 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:47:47,974 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:47:47,974 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:47:47,976 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 23 (Attempt 1)...

2024-12-23 01:48:04,310 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:48:04,324 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:48:04,324 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:48:04,325 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:48:04,326 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:48:04,327 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 24 (Attempt 1)...

2024-12-23 01:48:20,234 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:48:20,250 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:48:20,251 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:48:20,251 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:48:20,252 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:48:20,253 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 25 (Attempt 1)...

2024-12-23 01:48:38,290 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:48:38,305 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:48:38,306 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:48:38,306 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:48:38,307 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:48:38,308 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 26 (Attempt 1)...

2024-12-23 01:49:15,662 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:49:15,677 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:49:15,677 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:49:15,678 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:49:15,679 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:49:15,680 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 27 (Attempt 1)...

2024-12-23 01:49:34,110 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:49:34,123 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:49:34,123 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:49:34,124 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:49:34,125 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:49:34,125 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 28 (Attempt 1)...

2024-12-23 01:49:51,973 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:49:51,985 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:49:51,986 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:49:51,986 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:49:51,987 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:49:51,988 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 29 (Attempt 1)...

2024-12-23 01:50:07,226 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:50:07,240 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:50:07,240 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:50:07,241 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:50:07,242 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:50:07,243 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 30 (Attempt 1)...

2024-12-23 01:50:23,358 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:50:23,373 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:50:23,374 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:50:23,375 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:50:23,375 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:50:23,376 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 31 (Attempt 1)...

2024-12-23 01:50:37,396 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:50:37,409 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:50:37,410 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:50:37,410 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:50:37,411 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:50:37,412 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 32 (Attempt 1)...

2024-12-23 01:50:52,176 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:50:52,189 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:50:52,190 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:50:52,190 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:50:52,191 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:50:52,192 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 33 (Attempt 1)...

2024-12-23 01:51:16,075 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:51:16,089 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:51:16,089 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:51:16,090 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:51:16,091 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:51:16,091 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 34 (Attempt 1)...

2024-12-23 01:51:37,171 - recipe_logger - INFO - LLM 레시피 생성 완료

                                           user_info  \
0  {'user_allergy_ingredients': [], 'user_dislike...
1  {'user_allergy_ingredients': [], 'user_dislike...
2  {'user_allergy_ingredients': [], 'user_dislike...
3  {'user_allergy_ingredients': [], 'user_dislike...
4  {'user_allergy_ingredients': ['우유', '견과류'], 'u...

                                         recipe_info  \
0  {'_id': '67610699846f9e5eb975e532', 'title': '...
1  {'_id': '6761069a846f9e5eb9761021', 'title': '...
2  {'_id': '6761069a846f9e5eb9760836', 'title': '...
3  {'_id': '6761069a846f9e5eb9760639', 'title': '...
4  {'_id': '6761069a846f9e5eb976093b', 'title': '...

                                          generation  \
0  {'main_changes_from_original_recipe': ['🥗 닭가슴살...
1  {'main_changes_from_original_recipe': ['🍇 포도주스...
2  {'main_changes_from_original_recipe': ['🥣 양파는 ...
3  {'main_changes_from_original_recipe': ['🍋 레몬을 ...
4  {'main_changes_from_original_recipe': ['🥣 황태채 ...

                                         groundTruth
0  {'main_changes_from_original_recipe': ['🍗 연어 대...
1  {'main_changes_from_original_recipe': ['🍇 포도주스...
2  {'main_changes_from_original_recipe': ['🍄 버섯을 ...
3  {'main_changes_from_original_recipe': ['🍋 레몬 대...
4  {'main_changes_from_original_recipe': ['🥩 소고기를...
Processed data saved to data/groundTruth/final_groundTruth_f1.csv

In [4]:
# 데이터 로드
feature_num = 2  # 사용할 feature_num 설정

file_path = f'data/groundTruth/groundTruth_f{feature_num}.csv'
df = pd.read_csv(file_path)

# 이벤트 루프 생성 및 실행
loop = asyncio.get_event_loop()
loop.run_until_complete(generate(df, feature_num))

# 결과 저장
output_file = f'data/groundTruth/final_groundTruth_f{feature_num}.csv'
df.to_csv(output_file, index=False, encoding='utf-8-sig')
print(f"Processed data saved to {output_file}")

2024-12-23 01:51:37,215 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:51:37,215 - recipe_logger - INFO - langfuse prompt template 생성 완료

Processing row 0 (Attempt 1)...

2024-12-23 01:51:37,434 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:51:37,438 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:51:37,444 - recipe_logger - INFO - LLM 레시피 생성 중...
2024-12-23 01:51:54,021 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:51:54,034 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:51:54,035 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:51:54,036 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:51:54,037 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:51:54,038 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 1 (Attempt 1)...

2024-12-23 01:52:20,182 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:52:20,197 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:52:20,197 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:52:20,199 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:52:20,199 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:52:20,200 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 2 (Attempt 1)...

2024-12-23 01:52:36,798 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:52:36,812 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:52:36,812 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:52:36,813 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:52:36,814 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:52:36,815 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 3 (Attempt 1)...

2024-12-23 01:52:50,589 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:52:50,604 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:52:50,605 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:52:50,606 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:52:50,607 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:52:50,607 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 4 (Attempt 1)...

2024-12-23 01:53:09,985 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:53:09,999 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:53:10,000 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:53:10,000 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:53:10,001 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:53:10,002 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 5 (Attempt 1)...

2024-12-23 01:53:23,770 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:53:23,785 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:53:23,786 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:53:23,787 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:53:23,787 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:53:23,789 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 6 (Attempt 1)...

2024-12-23 01:53:40,279 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:53:40,293 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:53:40,294 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:53:40,295 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:53:40,296 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:53:40,297 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 7 (Attempt 1)...

2024-12-23 01:54:01,024 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:54:01,039 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:54:01,039 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:54:01,040 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:54:01,041 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:54:01,041 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 8 (Attempt 1)...

2024-12-23 01:54:31,858 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:54:31,880 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:54:31,881 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:54:31,882 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:54:31,883 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:54:31,884 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 9 (Attempt 1)...

2024-12-23 01:55:00,058 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:55:00,071 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:55:00,071 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:55:00,072 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:55:00,073 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:55:00,073 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 10 (Attempt 1)...

2024-12-23 01:55:19,355 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:55:19,402 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:55:19,403 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:55:19,407 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:55:19,443 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:55:19,448 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 11 (Attempt 1)...

2024-12-23 01:55:43,534 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:55:43,546 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:55:43,546 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:55:43,547 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:55:43,548 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:55:43,549 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 12 (Attempt 1)...

2024-12-23 01:56:02,097 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:56:02,110 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:56:02,110 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:56:02,112 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:56:02,112 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:56:02,113 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 13 (Attempt 1)...

2024-12-23 01:56:19,520 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:56:19,536 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:56:19,536 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:56:19,537 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:56:19,539 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:56:19,539 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 14 (Attempt 1)...

2024-12-23 01:56:39,034 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:56:39,048 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:56:39,048 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:56:39,049 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:56:39,051 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:56:39,052 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 15 (Attempt 1)...

2024-12-23 01:56:58,916 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:56:58,930 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:56:58,930 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:56:58,931 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:56:58,932 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:56:58,933 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 16 (Attempt 1)...

2024-12-23 01:57:17,423 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:57:17,438 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:57:17,438 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:57:17,439 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:57:17,440 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:57:17,440 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 17 (Attempt 1)...

2024-12-23 01:57:30,849 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:57:30,862 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:57:30,862 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:57:30,864 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:57:30,865 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:57:30,866 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 18 (Attempt 1)...

2024-12-23 01:57:50,355 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:57:50,368 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:57:50,368 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:57:50,369 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:57:50,369 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:57:50,370 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 19 (Attempt 1)...

2024-12-23 01:58:08,023 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:58:08,038 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:58:08,039 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:58:08,039 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:58:08,040 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:58:08,041 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 20 (Attempt 1)...

2024-12-23 01:58:25,346 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:58:25,359 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:58:25,360 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:58:25,361 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:58:25,362 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:58:25,363 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 21 (Attempt 1)...

2024-12-23 01:58:48,598 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:58:48,612 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:58:48,613 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:58:48,613 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:58:48,614 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:58:48,615 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 22 (Attempt 1)...

2024-12-23 01:58:59,932 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:58:59,947 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:58:59,947 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:58:59,948 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:58:59,949 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:58:59,950 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 23 (Attempt 1)...

2024-12-23 01:59:31,455 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:59:31,469 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:59:31,470 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:59:31,471 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:59:31,472 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:59:31,472 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 24 (Attempt 1)...

2024-12-23 01:59:50,115 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 01:59:50,129 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 01:59:50,129 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:59:50,130 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:59:50,131 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 01:59:50,132 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 25 (Attempt 1)...

2024-12-23 02:00:06,397 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:00:06,410 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:00:06,411 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:00:06,411 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:00:06,412 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:00:06,413 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 26 (Attempt 1)...

2024-12-23 02:00:24,162 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:00:24,177 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:00:24,178 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:00:24,179 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:00:24,179 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:00:24,180 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 27 (Attempt 1)...

2024-12-23 02:00:40,511 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:00:40,526 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:00:40,526 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:00:40,527 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:00:40,528 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:00:40,529 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 28 (Attempt 1)...

2024-12-23 02:00:58,005 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:00:58,019 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:00:58,020 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:00:58,020 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:00:58,021 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:00:58,022 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 29 (Attempt 1)...

2024-12-23 02:01:12,234 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:01:12,250 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:01:12,250 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:01:12,251 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:01:12,252 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:01:12,253 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 30 (Attempt 1)...

2024-12-23 02:01:31,794 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:01:31,806 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:01:31,806 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:01:31,807 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:01:31,808 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:01:31,809 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 31 (Attempt 1)...

2024-12-23 02:01:44,392 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:01:44,407 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:01:44,407 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:01:44,408 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:01:44,409 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:01:44,410 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 32 (Attempt 1)...

2024-12-23 02:02:00,059 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:02:00,074 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:02:00,074 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:02:00,075 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:02:00,076 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:02:00,077 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 33 (Attempt 1)...

2024-12-23 02:02:13,266 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:02:13,281 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:02:13,282 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:02:13,282 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:02:13,283 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:02:13,285 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 34 (Attempt 1)...

2024-12-23 02:02:31,620 - recipe_logger - INFO - LLM 레시피 생성 완료

                                           user_info  \
0  {'user_allergy_ingredients': [], 'user_dislike...
1  {'user_allergy_ingredients': [], 'user_dislike...
2  {'user_allergy_ingredients': [], 'user_dislike...
3  {'user_allergy_ingredients': [], 'user_dislike...
4  {'user_allergy_ingredients': ['우유', '견과류'], 'u...

                                         recipe_info  \
0  {'_id': '67610699846f9e5eb975e532', 'title': '...
1  {'_id': '6761069a846f9e5eb9761021', 'title': '...
2  {'_id': '6761069a846f9e5eb9760836', 'title': '...
3  {'_id': '6761069a846f9e5eb9760639', 'title': '...
4  {'_id': '6761069a846f9e5eb976093b', 'title': '...

                                          generation  \
0  {'main_changes_from_original_recipe': ['연어 대신 ...
1  {'main_changes_from_original_recipe': ['🍇 포도주스...
2  {'main_changes_from_original_recipe': ['양파와 감자...
3  {'main_changes_from_original_recipe': ['레몬을 굵은...
4  {'main_changes_from_original_recipe': ['소고기를 황...

                                         groundTruth
0  {'main_changes_from_original_recipe': ['🐟 연어 대...
1  {'main_changes_from_original_recipe': ['포도우유젤리...
2  {'main_changes_from_original_recipe': ['✨ 감자를 ...
3  {'main_changes_from_original_recipe': ['레몬차의 🍋...
4  {'main_changes_from_original_recipe': ['황태채 대신...
Processed data saved to data/groundTruth/final_groundTruth_f2.csv

In [2]:
# 데이터 로드
feature_num = 3  # 사용할 feature_num 설정

file_path = f'data/groundTruth/groundTruth_f{feature_num}.csv'
df = pd.read_csv(file_path)

# 이벤트 루프 생성 및 실행
loop = asyncio.get_event_loop()
loop.run_until_complete(generate(df, feature_num))

# 결과 저장
output_file = f'data/groundTruth/final_groundTruth_f{feature_num}.csv'
df.to_csv(output_file, index=False, encoding='utf-8-sig')
print(f"Processed data saved to {output_file}")

2024-12-23 02:35:06,124 - recipe_logger - INFO - json 출력 파서 초기화 완료.

Processing row 0 (Attempt 1)...

2024-12-23 02:35:06,752 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:35:06,957 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:35:07,133 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:35:07,313 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:35:07,314 - recipe_logger - INFO - LLM 레시피 생성 중...
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
2024-12-23 02:35:23,693 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:35:23,705 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:35:23,705 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:35:23,706 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:35:23,707 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:35:23,708 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:35:23,708 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 1 (Attempt 1)...

Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
2024-12-23 02:35:41,030 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:35:41,045 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:35:41,045 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:35:41,046 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:35:41,047 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:35:41,048 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:35:41,048 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 2 (Attempt 1)...

Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
2024-12-23 02:35:55,649 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:35:55,662 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:35:55,662 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:35:55,663 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:35:55,663 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:35:55,664 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:35:55,664 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 3 (Attempt 1)...

Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
2024-12-23 02:36:04,950 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:36:04,963 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:36:04,964 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:36:04,964 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:36:04,965 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:36:04,966 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:36:04,966 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 4 (Attempt 1)...

Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
2024-12-23 02:36:20,729 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:36:20,748 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:36:20,748 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:36:20,749 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:36:20,750 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:36:20,750 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:36:20,751 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 5 (Attempt 1)...

Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
2024-12-23 02:36:34,227 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:36:34,243 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:36:34,243 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:36:34,244 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:36:34,245 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:36:34,246 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:36:34,246 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 6 (Attempt 1)...

Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
2024-12-23 02:36:55,651 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:36:55,664 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:36:55,664 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:36:55,664 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:36:55,665 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:36:55,666 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:36:55,666 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 7 (Attempt 1)...

Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
2024-12-23 02:37:12,134 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:37:12,147 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:37:12,148 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:37:12,148 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:37:12,149 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:37:12,150 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:37:12,150 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 8 (Attempt 1)...

Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
2024-12-23 02:37:34,121 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:37:34,135 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:37:34,135 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:37:34,136 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:37:34,137 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:37:34,138 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:37:34,138 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 9 (Attempt 1)...

Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
2024-12-23 02:37:55,080 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:37:55,094 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:37:55,094 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:37:55,095 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:37:55,095 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:37:55,096 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:37:55,096 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 10 (Attempt 1)...

Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
2024-12-23 02:38:17,782 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:38:17,795 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:38:17,796 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:38:17,796 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:38:17,797 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:38:17,798 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:38:17,798 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 11 (Attempt 1)...

Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
2024-12-23 02:38:41,223 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:38:41,236 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:38:41,237 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:38:41,237 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:38:41,238 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:38:41,239 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:38:41,239 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 12 (Attempt 1)...

Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
2024-12-23 02:39:01,323 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:39:01,337 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:39:01,337 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:39:01,338 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:39:01,339 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:39:01,340 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:39:01,340 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 13 (Attempt 1)...

Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
2024-12-23 02:39:23,462 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:39:23,476 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:39:23,476 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:39:23,477 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:39:23,478 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:39:23,479 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:39:23,479 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 14 (Attempt 1)...

Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
2024-12-23 02:39:45,745 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:39:45,759 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:39:45,759 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:39:45,760 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:39:45,760 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:39:45,761 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:39:45,761 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 15 (Attempt 1)...

Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
2024-12-23 02:40:10,419 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:40:10,432 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:40:10,432 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:40:10,433 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:40:10,434 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:40:10,435 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:40:10,435 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 16 (Attempt 1)...

Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
2024-12-23 02:40:35,008 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:40:35,022 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:40:35,022 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:40:35,023 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:40:35,024 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:40:35,025 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:40:35,025 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 17 (Attempt 1)...

Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
2024-12-23 02:40:55,253 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:40:55,266 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:40:55,266 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:40:55,267 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:40:55,268 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:40:55,268 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:40:55,269 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 18 (Attempt 1)...

Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
2024-12-23 02:41:21,979 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:41:21,993 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:41:21,993 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:41:21,994 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:41:21,994 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:41:21,995 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:41:21,995 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 19 (Attempt 1)...

Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
2024-12-23 02:41:43,071 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:41:43,085 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:41:43,085 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:41:43,086 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:41:43,087 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:41:43,087 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:41:43,088 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 20 (Attempt 1)...

Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
2024-12-23 02:42:08,470 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:42:08,482 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:42:08,482 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:42:08,483 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:42:08,483 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:42:08,484 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:42:08,484 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 21 (Attempt 1)...

Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
2024-12-23 02:42:27,799 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:42:27,813 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:42:27,813 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:42:27,814 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:42:27,814 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:42:27,815 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:42:27,815 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 22 (Attempt 1)...

Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
2024-12-23 02:42:45,838 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:42:45,852 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:42:45,852 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:42:45,853 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:42:45,854 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:42:45,854 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:42:45,855 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 23 (Attempt 1)...

Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
2024-12-23 02:43:12,441 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:43:12,455 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:43:12,456 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:43:12,456 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:43:12,457 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:43:12,458 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:43:12,458 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 24 (Attempt 1)...

Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
2024-12-23 02:43:38,489 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:43:38,503 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:43:38,504 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:43:38,504 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:43:38,505 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:43:38,506 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:43:38,506 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 25 (Attempt 1)...

Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
2024-12-23 02:44:00,809 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:44:00,821 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:44:00,822 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:44:00,822 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:44:00,823 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:44:00,824 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:44:00,824 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 26 (Attempt 1)...

Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
2024-12-23 02:44:24,153 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:44:24,166 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:44:24,166 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:44:24,167 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:44:24,168 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:44:24,168 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:44:24,169 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 27 (Attempt 1)...

Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
2024-12-23 02:44:44,930 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:44:44,942 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:44:44,942 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:44:44,943 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:44:44,943 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:44:44,944 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:44:44,945 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 28 (Attempt 1)...

Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
2024-12-23 02:45:05,000 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:45:05,014 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:45:05,014 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:45:05,015 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:45:05,016 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:45:05,017 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:45:05,017 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 29 (Attempt 1)...

Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
2024-12-23 02:45:24,251 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:45:24,267 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:45:24,267 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:45:24,269 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:45:24,270 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:45:24,271 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:45:24,271 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 30 (Attempt 1)...

Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
2024-12-23 02:45:47,913 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:45:47,927 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:45:47,927 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:45:47,928 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:45:47,929 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:45:47,929 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:45:47,930 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 31 (Attempt 1)...

Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
2024-12-23 02:46:10,740 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:46:10,753 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:46:10,754 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:46:10,754 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:46:10,755 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:46:10,756 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:46:10,756 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 32 (Attempt 1)...

Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
2024-12-23 02:46:33,648 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:46:33,663 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:46:33,663 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:46:33,664 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:46:33,665 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:46:33,665 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:46:33,666 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 33 (Attempt 1)...

Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
2024-12-23 02:46:54,883 - recipe_logger - INFO - LLM 레시피 생성 완료
2024-12-23 02:46:54,895 - recipe_logger - INFO - json 출력 파서 초기화 완료.
2024-12-23 02:46:54,895 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:46:54,896 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:46:54,897 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:46:54,898 - recipe_logger - INFO - langfuse prompt template 생성 완료
2024-12-23 02:46:54,898 - recipe_logger - INFO - LLM 레시피 생성 중...

Processing row 34 (Attempt 1)...

Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
2024-12-23 02:47:22,382 - recipe_logger - INFO - LLM 레시피 생성 완료

                                           user_info  \
0  {'user_allergy_ingredients': [], 'user_dislike...
1  {'user_allergy_ingredients': [], 'user_dislike...
2  {'user_allergy_ingredients': [], 'user_dislike...
3  {'user_allergy_ingredients': [], 'user_dislike...
4  {'user_allergy_ingredients': ['우유', '견과류'], 'u...

                                         recipe_info  \
0  {'_id': '67610699846f9e5eb975e532', 'title': '...
1  {'_id': '6761069a846f9e5eb9761021', 'title': '...
2  {'_id': '6761069a846f9e5eb9760836', 'title': '...
3  {'_id': '6761069a846f9e5eb9760639', 'title': '...
4  {'_id': '6761069a846f9e5eb976093b', 'title': '...

                                          generation  \
0  {'original_recipe_food_group_composition': [{'...
1  {'original_recipe_food_group_composition': [{'...
2  {'original_recipe_food_group_composition': [{'...
3  {'original_recipe_food_group_composition': [{'...
4  {'original_recipe_food_group_composition': [{'...

                                         groundTruth
0  {'original_recipe_food_group_composition': [{'...
1  {'original_recipe_food_group_composition': [{'...
2  {'original_recipe_food_group_composition': [{'...
3  {'original_recipe_food_group_composition': [{'...
4  {'original_recipe_food_group_composition': [{'...
Processed data saved to data/groundTruth/final_groundTruth_f3.csv

Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Forbidden"}')

In [61]:
df_cp = df.copy().reset_index(drop=True)

In [67]:
feature_eval_result

{'main_changes_from_original_recipe': ['연어를 닭가슴살로 변경했어요! 🐟➡️🍗',
  '발사믹식초를 레몬즙으로 바꿨어요! 🍇➡️🍋',
  '어린잎채소는 그대로 두었어요! 🥗✨',
  '조리 과정을 간단하게 정리했어요! 📋✂️'],
 'reason_for_changes': ['닭가슴살은 필수 재료로 사용해야 하니 연어 대신 넣었어요! 🍗💪',
  '발사믹식초 대신 레몬즙을 사용하면 상큼함을 유지할 수 있어요! 🍋💖',
  '어린잎채소는 신선한 식감을 주기 때문에 그대로 두었어요! 🥗🌱',
  '조리 난이도가 중급인 사용자를 위해 과정을 간단하게 정리했어요! 🛠️✨'],
 'recipe_cooking_order': ['닭가슴살은 구워서 깍둑썰기 해주세요.',
  '구운 닭가슴살에 후춧가루와 레몬즙으로 마리네이드 해주세요.',
  '어린잎채소는 찬물에 담궈 물기를 빼주세요.',
  '레몬즙과 올리브오일을 섞어 드레싱을 만들어주세요.',
  '드레싱에 마리네이드한 닭가슴살과 어린잎채소를 섞어 접시에 담아주세요.'],
 'recipe_cooking_time': '약 20분',
 'recipe_difficulty': '중급',
 'recipe_ingredients': ['닭가슴살(150g)',
  '레몬(1/4개)',
  '레몬즙(50g)',
  '어린잎채소(30g)',
  '후춧가루(0.01g)',
  '올리브오일(20g)'],
 'recipe_menu_name': '닭가슴살 샐러드',
 'recipe_tips': ['드레싱에 소금을 추가하지 않아도 레몬과 올리브오일의 조화로 맛있어요! 🍋✨',
  '닭가슴살을 미리 구워두면 더 간편하게 만들 수 있어요! 🔥🍗'],
 'recipe_type': '샐러드',
 'unchanged_parts_and_reasons': ['어린잎채소는 신선한 식감을 주기 때문에 변경하지 않았어요! 🥗🌿',
  '후춧가루는 간단한 양념으로 요리의 풍미를 살려주기 때문에 그대로 두었어요! 🌶️👌']}

In [58]:
user_info

{'user_allergy_ingredients': [],
 'user_dislike_ingredients': [],
 'user_spicy_level': '3단계',
 'user_cooking_level': '중급',
 'user_owned_ingredients': ['닭가슴살', '두부', '브로콜리'],
 'user_basic_seasoning': ['소금', '후추', '올리브유'],
 'must_use_ingredients': ['닭가슴살']}

KeyError: "Input to PromptTemplate is missing variables {'recipe_info', 'user_info'}.  Expected: ['recipe_info', 'recipe_keyIngredients_tasty', 'user_info'] Received: ['recipe_keyIngredients_tasty']\nNote: if you intended {recipe_info} to be part of the string and not a variable, please escape it with double curly braces like: '{{recipe_info}}'.\nFor troubleshooting, visit: https://python.langchain.com/docs/troubleshooting/errors/INVALID_PROMPT_INPUT"

In [138]:
import asyncio
import time
import sys
sys.path.append('../')  # 상위 디렉토리의 src 폴더를 경로에 추가

from src.recipe_change_origin import langfuse_tracking, get_system_prompt, choose_feature, ChangeRecipe, RecipeChangeBalanceNutrition 
from langchain_openai import ChatOpenAI
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import JsonOutputParser, StrOutputParser
from src.logger import logger_eval
import pandas as pd
import asyncio

llm = ChatOpenAI(
        model="gpt-4o",
        temperature=0.0,
        max_tokens=1000,
        timeout=40
    )
logger_eval.info("LLM 초기화 완료.")

async def generate_test_dataset(prompt, df, new_column, batch_size=5, max_concurrent_tasks=3):
    prompt = get_system_prompt(prompt)
    llm_chain = prompt | llm | StrOutputParser()

    logger_eval.info("LLM 레시피 생성 중...")
    semaphore = asyncio.Semaphore(max_concurrent_tasks)  # 동시 실행 제한

    async def process_task(i, langfuse_handler):
        async with semaphore:
            for _ in range(3):  # 최대 3번 재시도
                try:
                    result = await llm_chain.ainvoke(
                        input={"user_info": df.user_info[i], "recipe_info": df.recipe_info[i]},
                        config={"callbacks": [langfuse_handler]},
                    )
                    return result
                except Exception as e:
                    if "rate limit" in str(e).lower():
                        logger_eval.warning(f"Rate limit hit for index {i}. Retrying...")
                        await asyncio.sleep(0.5)  # 대기 후 재시도
                    else:
                        logger_eval.error(f"Error at index {i}: {e}")
                        return e  # 재시도 중 에러 발생 시 반환
            logger_eval.error(f"Max retries exceeded for index {i}")
            return None

    for start in range(0, len(df), batch_size):
        end = start + batch_size
        langfuse_handler = langfuse_tracking()
        tasks = [process_task(i, langfuse_handler) for i in range(start, min(end, len(df)))]
        results = await asyncio.gather(*tasks, return_exceptions=True)

        for i, result in enumerate(results):
            if result is None or isinstance(result, Exception):
                logger_eval.error(f"Error at index {start + i}: {result}")
            else:
                df.at[start + i, new_column] = result

        # 요청 사이 지연 추가 (토큰 사용량 분산)
        await asyncio.sleep(0.1)  # 100ms 지연

    logger_eval.info("LLM 레시피 생성 완료")
    return df

In [139]:
# user_info, recipe_info가 있는 dataset -> 결과는 langfuse 2024.12.18 오전 9:9~9:10분꺼부터 보기
df = pd.read_json('data/combined_dataset.json')

# 비동기 함수 실행
df_tasty = await generate_test_dataset("find_keyIngredients_tasty", df, "expected_output")
df_tasty.describe()

,user_info,recipe_info
count,35,35
unique,10,35
top,"{'user_allergy_ingredients': [], 'user_dislike_ingredients': [], 'user_spicy_level': '3단계', 'user_cooking_level': '중급', 'user_owned_ingredients': ['닭가슴살', '두부', '브로콜리'], 'user_basic_seasoning': ['소금', '후추', '올리브유'], 'must_use_ingredients': ['닭가슴살']}","{'_id': '67610699846f9e5eb975e532', 'title': '연어샐러드', 'type_key': '샐러드', 'method_key': '회', 'servings': '1인분', 'cooking_time': '', 'difficulty': '', 'ingredients': ['연어(150g)', '레몬(1/4개)', '발사믹식초(50g)', '어린잎채소(30g)', '후춧가루(0.01g)', '올리브오일(20g)'], 'cooking_steps': ['1. 연어는 깍둑썰기한다.', '2. 썰어 놓은 연어는 후춧가루와 레몬으로 마리네이드한다.', '3. 어린잎은 찬물에 담궈둔다.', '4. 담궈 놓은 어린잎을 체에 받쳐 물기를 뺀다.', '5. 레몬과 올리브오일을 섞는다.', '6. ?번에 발사믹소스를 넣고 연어 샐러드 양념을 만들고, 접시에 연어와 물기를 뺀 어린잎을 담는다.'], 'tips': ['발사믹소스에 레몬과 올리브오일을 섞어 별도의 소금을 넣지 않을 수 있어요.']}"
freq,4,1

In [121]:
# user, recipe 정보만 저장
# df_tasty.iloc[:,:-1].to_csv("data/test_userRecipe.csv", index=False)

# user, recipe, 맛분석 결과 저장
df_tasty.to_csv("data/test_userRecipeTasty.csv", index=False)

In [124]:
df_tasty[:2]

,user_info,recipe_info,recipe_keyIngredients_tasty
0,"{'user_allergy_ingredients': [], 'user_dislike_ingredients': [], 'user_spicy_level': '3단계', 'user_cooking_level': '중급', 'user_owned_ingredients': ['닭가슴살', '두부', '브로콜리'], 'user_basic_seasoning': ['소금', '후추', '올리브유'], 'must_use_ingredients': ['닭가슴살']}","{'_id': '67610699846f9e5eb975e532', 'title': '연어샐러드', 'type_key': '샐러드', 'method_key': '회', 'servings': '1인분', 'cooking_time': '', 'difficulty': '', 'ingredients': ['연어(150g)', '레몬(1/4개)', '발사믹식초(50g)', '어린잎채소(30g)', '후춧가루(0.01g)', '올리브오일(20g)'], 'cooking_steps': ['1. 연어는 깍둑썰기한다.', '2. 썰어 놓은 연어는 후춧가루와 레몬으로 마리네이드한다.', '3. 어린잎은 찬물에 담궈둔다.', '4. 담궈 놓은 어린잎을 체에 받쳐 물기를 뺀다.', '5. 레몬과 올리브오일을 섞는다.', '6. ?번에 발사믹소스를 넣고 연어 샐러드 양념을 만들고, 접시에 연어와 물기를 뺀 어린잎을 담는다.'], 'tips': ['발사믹소스에 레몬과 올리브오일을 섞어 별도의 소금을 넣지 않을 수 있어요.']}","### 레시피 맛 설명\n연어샐러드는 신선한 연어의 부드러운 식감과 어린잎채소의 아삭함이 조화를 이루는 요리입니다. 발사믹식초와 레몬의 상큼한 맛이 연어의 풍미를 돋우며, 올리브오일이 전체적으로 부드러운 맛을 더해줍니다. 후춧가루는 약간의 매콤함을 더해 맛의 균형을 잡아줍니다.\n\n### 핵심 재료와 비핵심 재료\n- **핵심 재료:**\n - **연어:** 이 요리의 주재료로, 신선한 해산물의 맛과 부드러운 식감을 제공합니다.\n - **어린잎채소:** 신선한 채소의 아삭한 식감과 상큼한 맛을 더해줍니다.\n - **발사믹식초:** 샐러드 드레싱의 기본이 되는 재료로, 상큼하고 달콤한 맛을 제공합니다.\n - **레몬:** 연어의 비린 맛을 잡아주고 상큼함을 더해줍니다.\n\n- **비핵심 재료:**\n - **후춧가루:** 약간의 매콤함을 더해주는 역할을 하지만, 없어도 큰 맛의 변화는 없습니다.\n - **올리브오일:** 드레싱의 부드러움을 더해주지만, 다른 오일로 대체 가능할 수 있습니다.\n\n### 재료 변경 및 이유\n- **연어 → 닭가슴살:** 사용자가 반드시 사용해야 하는 재료인 닭가슴살을 활용합니다. 닭가슴살은 연어와는 다른 식감과 맛을 제공하지만, 단백질 공급원으로서의 역할을 유지할 수 있습니다. 닭가슴살은 부드럽고 담백한 맛을 가지고 있어, 발사믹식초와 레몬 드레싱과 잘 어울립니다.\n- **어린잎채소, 발사믹식초, 레몬, 후춧가루, 올리브오일:** 이 재료들은 그대로 유지합니다. 닭가슴살과도 잘 어울리며, 샐러드의 신선함과 드레싱의 맛을 유지하는 데 필수적입니다.\n\n이러한 변경은 사용자의 재료 제약 조건을 충족하면서도 원래 레시피의 맛과 조화를 최대한 유지하려는 목적을 가지고 있습니다."
1,"{'user_allergy_ingredients': [], 'user_dislike_ingredients': ['토마토', '오이'], 'user_spicy_level': '2단계', 'user_cooking_level': '초급', 'user_owned_ingredients': ['계란', '감자', '스팸'], 'user_basic_seasoning': ['간장', '설탕', '후추'], 'must_use_ingredients': ['계란']}","{'_id': '6761069a846f9e5eb9761021', 'title': '포도우유젤리 만들기', 'type_key': '디저트', 'method_key': '끓이기', 'servings': '3인분', 'cooking_time': '30분 이내', 'difficulty': '초급', 'ingredients': ['포도주스(300g)', '설탕(50g)', '레몬즙(1작은술)', '젤라틴(가루)(15g)', '물(젤라틴)(5-6큰술)', '우유(200g)', '생크림(100g)', '설탕(30g)', '바닐라오일(2-3방울)', '젤라틴(가루)(15g)', '물(젤라틴)(5-6큰술)'], 'cooking_steps': ['먼저 찬물에 가루 젤라틴을 불려 주세요. 가루 젤라틴을 사용하는 법은 가루젤라틴 양의 5-6배의 찬물에 불려서 사용하시면 됩니다. 불리는 시간은 10분 정도이면 됩니다. 전 2가지 젤리를 만들 것이기 때문에 2개분의 젤라틴을 찬물에 불렸습니다.', '냄비에 포도주스(또는 기타 주스)와 설탕을 넣고 약한 불에 올려 설탕이 녹을 정도로 데워 주세요. 끓이시면 안됩니다.', '찬물에 불린 젤라틴을 넣고 잘 저어 완전히 녹여 주세요. 간혹 젤라틴이 덩어리져 잘 안 풀리다는 분이 계신데 이럴 때에는 체에 한 번 걸러 주세요.마지막에 레몬쥬스를 넣고 잘 섞어 주세요.', '틀에 1/2 정도만 붓고 냉장고에서 1시간 이상 굳혀 주세요.', '파나코타는 포도젤리가 다 굳은 후 만드셔야 합니다. 냄비에 우유, 생크림, 설탕, 바닐에오일을 넣고 중간 불에서 데워 주세요. 설탕이 녹이기 위한 것이니 끓이지는 마세요.', '역시 찬물에 불린 젤라틴을 넣고 잘 저어 젤라틴을 잘 녹여 주세요.', '체에 한 번 걸은 후 상온에서 약간 식혀 포도젤리 위에 부어 냉장고에서 1시간 이상 굳혀 주세요.'], 'tips': ['젤리 틀에서 잘 꺼내는 법은? 젤리는 특성상 따뜻한 물이 닿으면 살짝 녹습니다. 이 성질을 이용하여서 굳은 젤리 그릇의 바닥을 뜨거운 물에 담갔다가 뒤집으면 아주 깨끗하게 잘 떨어집니다. 그러나 너무 오래 담가 놓으면 예쁜 모양이 나오지 않는답니다.']}","### 레시피 맛 설명\n포도우유젤리는 상큼한 포도 맛과 부드러운 우유의 조화가 돋보이는 디저트입니다. 포도주스의 상큼함과 레몬즙의 산미가 젤리의 상쾌한 맛을 더해주며, 우유와 생크림의 부드러움이 파나코타 층에서 느껴집니다. 바닐라오일은 은은한 향을 더해 전체적인 맛을 풍부하게 만들어 줍니다.\n\n### 핵심 재료와 비핵심 재료\n- **핵심 재료:**\n - **포도주스:** 젤리의 주된 맛을 결정하는 재료로, 상큼한 포도 맛을 제공합니다.\n - **젤라틴:** 젤리의 형태를 잡아주는 필수적인 재료입니다.\n - **우유와 생크림:** 파나코타 층의 부드러움과 크리미한 맛을 제공합니다.\n\n- **비핵심 재료:**\n - **설탕:** 단맛을 추가하지만, 다른 감미료로 대체 가능하여 비핵심으로 분류됩니다.\n - **레몬즙:** 산미를 더하지만, 없어도 큰 맛의 변화는 없습니다.\n - **바닐라오일:** 향을 더해주지만, 필수적이지는 않습니다.\n\n### 재료 변경 제안\n사용자의 정보와 제약 조건에 따라 레시피를 변경할 필요는 없습니다. 사용자는 특정 알레르기나 싫어하는 재료가 없으며, 포도우유젤리 레시피에 포함된 재료들은 모두 사용 가능합니다. 또한, 사용자가 반드시 사용해야 하는 재료로 '계란'이 있지만, 이 레시피에 계란을 추가하는 것은 맛과 질감에 큰 영향을 미칠 수 있으므로, 레시피의 본질을 유지하기 위해 계란을 추가하지 않는 것이 좋습니다.\n\n따라서, 레시피는 그대로 유지하며, 사용자가 소유한 기본 조미료(간장, 설탕, 후추)는 이미 레시피에 포함되어 있어 추가적인 변경이 필요하지 않습니다."

### dataset에 레시피 영양성분 분석 결과 추가

In [ ]:
df = pd.read_json('data/combined_dataset.json')
df_cp = df.copy().reset_index(drop=True)
final_df = await generate_test_dataset("generate_food_group_ratio", df_cp, "expected_output")
final_df.describe()

In [ ]:
final_df.to_csv("data/test_groupRatio.csv", index=False)

### dataset에 레시피 영양성분 분석 결과 추가

In [ ]:
df = pd.read_json('data/combined_dataset.json')
df_cp = df.copy().reset_index(drop=True)
final_df = await generate_test_dataset("generate_food_group_ratio", df_cp, "expected_output")
final_df.describe()

# 데이터 가독성을 높여 출력하는 함수

In [ ]:

def display_columns_with_format(df, col1, col2):
    for i, row in df.iterrows():
        print(f"Row {i + 1}:")
        print(f"--- {col1} ---")
        print(row[col1])  # 딕셔너리나 JSON 형태를 보기 좋게 출력
        print(f"\n--- {col2} ---")
        print(row[col2])  # 마크다운 텍스트 그대로 출력
        print("\n" + "=" * 40 + "\n")

# 함수 호출
display_columns_with_format(df, "recipe_info", "original_recipe_food_group_composition")